config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :customers, :controllers =>{
    registrations: 'customers/registrations',
    sessions: 'customers/sessions',
    passwords: 'customers/passwords'
  }

  get 'customers/show'
  ActiveAdmin.routes(self)
  root to: "products#index"
    resources :products
    resources :customers, only: [:show] do
      resources :messages, only: [:index, :create] do
        get :auto, on: :collection
      end
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :customer
  mount_uploader :image, ImageUploader

  validates :text, presence: true, length: {maximum: 300}
  
  enum roll:{"admin":0, "customer":1}
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_customer! ,unless: :current_admin_user
  before_action :ensure_customer ,unless: :current_admin_user
  before_action :set_customer


  def index
    @messages = @customer.messages
    @message = Message.new
  end

  def create
    @message = @customer.messages.new(message_params)
    if current_admin_user
      @message.roll = 0
    else
      @message.roll = 1
    end
    if @message.save
    else
      @messages =@customer.messages
      flash.now[:alert] ='メッセージを入力してください'
      render :index
    end
  end

  def auto
    @messages = @customer.messages
    last_message_id = params[:id].to_i
    @messages =@customer.messages.includes(:customer).where("id > #{last_message_id}")
    @flag = @messages.present? ?  "true" : "false"
  end


  private
  def message_params
    params.require(:message).permit(:text, :image)
  end

  def set_customer
    @customer=Customer.find(params[:customer_id])
  end

  def ensure_customer
    if current_customer.id != params[:customer_id].to_i
      redirect_to root_path
    end
  end
end

app/views/messages/_message.html.erb
<% if message.roll == 'customer' %>
  <div class="message customer" data-mesage_id="<%=message.id%>">
    <p class="message-text"><%= message.text%></p>

    <%if message.image.present?%>
      <div><%= image_tag message.image.url, class:"message-image"%></div>
    <% end %>

    <p class="message-date"><%= message.created_at.strftime("%-m月%-d日 %-H時%-M分")%></p>
  </div>
<% else %>
  <div class="message admin" data-mesage_id="<%=message.id%>">
    <p class="message-text"><%= message.text%></p>

    <%if message.image.present?%>
      <div><%= image_tag message.image.url, class:"message-image"%></div>
    <% end %>

    <p class="message-date"><%= message.created_at.strftime("%-m月%-d日 %-H時%-M分")%></p>
  </div>
<% end %>

app/views/messages/auto.js.erb
scroll_flag = <%= @flag %>;
$('.messages-main__chat').append('<%= j(render partial: 'message',collection: @messages) %>')
if (scroll_flag == true){
    var last_message_height =$('.messages-main').get(0).scrollHeight
     $('.messages-main').animate({scrollTop:last_message_height},1000);
}

app/views/messages/create.js.erb
$('.messages-main__chat').append('<%= j(render partial: 'message',locals: { message: @message }) %>')
$('.messages-form-text').val('');
var last_message_height =$('.messages-main').get(0).scrollHeight
$('.messages-main').animate({scrollTop:last_message_height},function(){
  location.reload()
});

app/views/messages/index.html.erb
<div class="message__wrapper"> 
  <div class="messages">
    <div class="messages-image"></div>
    <ul class="messages-nav">
      <li><%= @customer.name%> 様</li>
      <li><%=link_to "log-out", destroy_customer_session_path,method:'delete'%></li>
      <li><%=link_to "top", root_path%></li>
    </ul>

    <div class="messages-main">
      <div class="messages-main__chat">
        <%= render @messages%>
      </div>
      <div class="main__user">
      </div>
    </div>
    <%= form_with model:[@customer, @message],id:'message_form' do |f|%> 
      <div class="messages-form">
        <%= f.text_area :text ,placeholder:"message" ,class:'messages-form-text'%>
        <%= f.submit '送信' ,id:'messages-form-btn'%>
        <%if admin_user_signed_in?%>
          <%= f.file_field :image ,id:'messages-form-image'%>
        <% end %>
    </div>
    <%end%>
  </div>
</div>