config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :customers, :controllers =>{
    registrations: 'customers/registrations',
    sessions: 'customers/sessions',
    passwords: 'customers/passwords'
  }

  get 'customers/show'
  ActiveAdmin.routes(self)
  root to: "products#index"
    resources :products
    resources :customers, only: [:show] do
      resources :messages, only: [:index, :create] do
        get :auto, on: :collection
      end
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_images, dependent: :destroy
  accepts_nested_attributes_for :product_images,allow_destroy: true
  mount_uploader :image, ImageUploader
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :current_admin_user?,except: [:index,:show]
  before_action :set_product,except: [:index,:new, :create]

  def index 
    @products = Product.all.limit(4)
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
    @product.product_images.build
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_root_path
    end
  end

  def edit
    @product.product_images.build
  end

  def update
    if @product.update(product_params)
      redirect_to admin_root_path
    end
  end

  def destroy
    @product.destroy
    redirect_to admin_root_path
  end

  private
  def product_params
    params.require(:product).permit(:name,:text,:image,:date,:place,:purpose,:scale,:site_area,:building_area,:architectural_area, product_images_attributes: [:_destroy,:id,:src])
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def current_admin_user?
    redirect_to root_path unless current_admin_user
  end 

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product-form.html.erb
<%= form_with model:@product, local: true do |f|%> 
  <div class="form">
    <div class="form__container">
    <%= link_to "top" , root_path %>
      <div class="form__content">
        <%=f.label :name ,"name",class:"label"%>
        <%= f.text_field :name ,class:"input"%>
      </div>
      <div class="form__content">
        <%=f.label :text ,"text",class:"label"%>
        <%= f.text_area :text,class:"form_text"%>
      </div>
      <div class="main__image image_form">
        <p>main-image</p>
        <div class="main__image-select">
          <% if @product.image.present?%>
            <%= image_tag @product.image.url, class:'output'%>
          <% end %>
        </div>
          <%=f.label :image ,class:"main__image-select-label",data:{index:"0"} do%>
            <%= f.file_field :image ,class:"file_field"%>
          <% end %>

      </div>
     <p class="works_heading"> works-image </p>

          <div class="works_output_area">
            <% @product.product_images.each_with_index do |image ,i|%>
              <%if image.persisted?%>
                <div class="image-wrapper">
                  <%= image_tag image.src.url, class:"works_output" %>
                  <div class="image_remove" data-index = <%=i%> >削除</div>
                </div>
              <% end %>
            <%end%>
          </div>

        <div class="works_input_area"> 
          ここをクリックして写真を添付
          <%=f.fields_for :product_images do |image|%>
            <%=image.label :src ,class:"works_input",data:{index:@product.product_images.count}  do%>
              <%= image.file_field :src ,class:"works_file_field"%>
                <%if image.object.persisted?%> 
                  <%= image.check_box :_destroy,class:'hidden'%>
                  <%= image.label :_destroy, "",class:"image_destroy hidden"%>
                <% end %>
              <%end%>
          <% end %>
        </div>
      
      <div class="form__content">
        <%=f.label :date ,"竣工年月日",class:"label"%>
        <%= f.date_select :date,{use_two_digit_numbers:true},class:"input date"%>
      </div>
      <div class="form__content">
        <%=f.label :place ,"所在地",class:"label"%>
        <%= f.text_field :place,class:"input"%>
      </div>
      <div class="form__content">
        <%=f.label :purpose ,"主要用途",class:"label"%>
        <%= f.text_field :purpose,class:"input"%>
      </div>
      <div class="form__content">
        <%=f.label :scale ,"構造規模",class:"label"%>
        <%= f.text_field :scale,class:"input"%>
      </div>
      <div class="form__content">
        <%=f.label :site_area ,"敷地面積",class:"label"%>
        <%= f.text_field :site_area,class:"input"%>
      </div>
      <div class="form__content">
        <%=f.label :building_area ,"建築面積",class:"label"%>
        <%= f.text_field :building_area,class:"input"%>
      </div>
      <div class="form__content">
        <%=f.label :architectural_area ,"延べ床面積",class:"label"%>
        <%= f.text_field :architectural_area,class:"input"%>
      </div>
      <%= f.submit "send" ,class:"buttom"%>
    </div>
  </div>
<%end%>

app/views/products/_product.html.erb
<%=link_to product_path(product) do%>
  <div class="card" data-product-id =<%=product.id%> >
    <%=image_tag product.image.url, class:"card-image"%>
  </div>
<%end%>

app/views/products/_show.html.erb
<div class="show">
  <div class="show__data">
    <ul class="show__data-top">
      <li>所在地：<%= @product.place%></li>
      <li>竣工年月日：<%= @product.date.strftime('%Y/%m/%d')%></li>
    </ul>
    <ul class="show__data-bottom">
      <li>主要規模：<%= @product.purpose%></li>
      <li>構造規模：<%= @product.scale%></li>
      <li>敷地面積：<%= @product.site_area%>m2</li>
      <li>建築面積：<%= @product.building_area%>m2</li>
      <li>延べ床面積：<%= @product.architectural_area%>m2</li>
    </ul>
  </div>
    <div class="show__slide">
      <div class="show__slide-wrapper">
        <i class="fas fa-caret-square-left prev"></i>
        <i class="fas fa-caret-square-right next"></i>
        <%@product.product_images.each_with_index do |image, i|%>
          <%= image_tag image.src.url ,class:'show__image',data:{index:i}%>
        <% end %>
      </div>
      <ul class="show__slide__bar">
        <%@product.product_images.each_with_index do |image, i|%>
          <li><%= image_tag image.src.url, class:"show__bar-image" ,data:{index:i}%></li>

        <% end %>
      </ul>
    </div>
</div> 

app/views/products/edit.html.erb
<div class="new_product">
登録変更
<%= link_to "delete", product_path(@product) ,method: "delete"%> 
<%= render 'product-form'%>
</div>

app/views/products/index.html.erb
<div class="products">
  <%= render 'layouts/nav'%>
  <section class='top'>
    <%# <h4 class="top__message"><span>光</span>を感じる</h4>
    <h4 class="top__message"><span>緑</span>を感じる</h4>
    <h4 class="top__message"><span>水</span>を感じる</h4>
    <h4 class="top__message"><span>人</span>を感じる</h4> %>

    <div class="top__left">
    <h2 class="top__left-message">
      行き止まりの無い家<br/>
      すみませんか？
      <p>私が育った住宅は行き止まりがなく,子どもながらにかくれんぼや、鬼ごっこをしたことを覚えています。未来をつなぐ子ども達の記憶に残るような、住まいを作りたいと思います。
      </p>

    </h2>
    </div>

    <div class="top__card">
       <div class="top__card-letter">
        子どもの<span>心に残る</span>空間作りを約束します
       </div>

      <div class="top__card-image">
          <div class='reflection'></div>
        <%=image_tag "/スケッチ.png" ,class:"hand_writing"%>
      </div>
    </div>
  </section>

    <h3 class="works__heading">
    </h3>
  <section class="works">
    <div class="works__left">
      <div class="works__slide">
        <div class="works__slide-message"> </div>



        <% @products.each do |product|%>
              <div class="title"><%= product.name%></div>
          <%= image_tag product.image.url,class:"works__slide-image"%>
        <%end%>
      </div>

        <ul class="works__left-bar">
          <% @products.each do |product|%>
            <%= link_to product_path(product),remote:true do%>
              <li>
                <div class="masking"><%= product.name%></div>
                <%= image_tag product.image.url ,class:"works__left-bar-image"%>
              </li>
            <% end %>
          <%end%>
        </ul>
    </div>
    <div class="works__box">
        <div class="works__box-dummy"></div>

      <h2 class="works__box-name">works</h2>
      <p class="works-text">
        
      </p>
    </div>
  </section>
  <h3></h3>

  <%# <section class="about">
    <%= image_tag "/about.png"%>

  <%# </section> %>
  
  <section class="contact">

  <div class="login-btn">contact<div>
  </section>
</div>

app/views/products/new.html.erb
<div class="new_product">
新規登録
<%= render 'product-form'%>
</div>

app/views/products/show.html.erb
<div class="show">
  <div class="container">
  <div class="dummy"></div>
    <%= render 'layouts/nav'%>
    <div class="show__slide">
    <div class="show__slide-title">
      <h2 class="show-name"><%= @product.name%></h2>
      <h3 class="show-title"><%= @product.text%></h3>
    </div>
    <div class="show__slide-data">
      多分これは縄文時代に作った遺跡をリフォームして、現代風に変えた建築物。入り口がたて穴なのが興味をそそります。あと屋根には登れません。
    </div>
      <div class="show__slide-left">
        <div class="show__slide-left-frame">
        <i class="far fa-caret-square-left"></i>
        <i class="far fa-caret-square-right"></i>
          <% @works.each do |work|%>
            <%=image_tag work.image.url ,class:"show__slide-left-frame-image image-style"%>
           <%end%>
        </div>
       </div>
        <div class="show__slide-right">
          <div class="show__slide-right-frame">
            <% @works.each do |work|%>
              <%=image_tag work.image.url ,class:"show__slide-right-frame-image image-style"%>
           <%end%>

          </div>
      </div>
    </div>
    <div class="slide_bar">
        <div class="slide_bar-prev">
          <i class="fas fa-caret-left"></i>
        </div>
        <div class="slide_bar-wrapper">
      <% @works.each do |work|%>
          <%=image_tag work.image.url ,class:"slide_bar-image image-style"%>
      <%end%>
        </div>
        <div class="slide_bar-next">
          <i class="fas fa-caret-right"></i>
        </div>
  </div>
</div>


<%= link_to "work_new" ,new_product_work_path(@product), class:"buttom"%>
    <%=link_to "edit" ,edit_product_path(@product), class:"buttom"%>

app/views/products/show.js.erb
$(function(){
$('.works__slide').html('<%= j(render partial: 'show') %>')

clearInterval(product_slide)
var works_height=$(".works__slide").offset().top - $('.nav').height()
console.log($('.nav').height())
$('html, body').animate({scrollTop:works_height});

$('.works-text').text('<%= @product.text %>')

$('.show').css("display","none")
$('.show').fadeIn(1000)
$('.works__box-name').html('<h1 class="appear"><%= @product.name %></h1>')

var works_height = $('.works').offset().top - $('.nav').height()
$('html ,body').animate({scrollTop:works_height})
$('.show__image').css("display","none")
$('.show__image').eq(0).fadeIn()
$(`.show__bar-image[data-index = ${j}]`).css("background","aqua")

})